/**
 * Dummy provider — simulates LLM responses with no network calls or API keys.
 *
 * Useful for local demos, CI pipelines, and integration tests.
 *
 * Optional environment variables:
 *   DUMMY_DELAY_MS   — artificial latency per step in ms (default: 200)
 *   DUMMY_STEPS      — number of progress steps to emit   (default: 4)
 */

import type { LLMProvider, LLMRequest, LLMResponse, LLMMessage, ProgressCallback } from './llm-provider';

const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms));

export interface DummyProviderConfig {
  /** Artificial delay per simulated step in ms. Default: 200 */
  delayMs?: number;
  /** Number of simulated reasoning steps. Default: 4 */
  steps?: number;
}

const STEPS = [
  'Parsing task…',
  'Identifying objectives…',
  'Formulating plan…',
  'Generating response…',
];

export class DummyProvider implements LLMProvider {
  readonly name = 'Dummy';

  private readonly delayMs: number;
  private readonly steps: string[];

  constructor(config: DummyProviderConfig = {}) {
    const delayMs = config.delayMs
      ?? (process.env['DUMMY_DELAY_MS'] ? parseInt(process.env['DUMMY_DELAY_MS'], 10) : 200);
    const stepCount = config.steps
      ?? (process.env['DUMMY_STEPS'] ? parseInt(process.env['DUMMY_STEPS'], 10) : 4);

    this.delayMs = delayMs;
    this.steps = STEPS.slice(0, Math.max(1, stepCount));
  }

  async complete(request: LLMRequest, onProgress?: ProgressCallback): Promise<LLMResponse> {
    const msgs = request.messages;
    const userMessage = [...msgs].reverse().find((m: LLMMessage) => m.role === 'user')?.content ?? '';

    for (const step of this.steps) {
      if (onProgress) onProgress(step);
      await sleep(this.delayMs + Math.random() * this.delayMs);
    }

    const content = [
      `Task   : ${userMessage}`,
      `Model  : ${request.model ?? 'dummy-1'}`,
      `Status : Completed (dummy model — no real inference performed)`,
      ``,
      `─────────────────────────────────────────────────────────────────`,
      `This response was generated by DummyProvider.`,
      `Replace LLM_PROVIDER=dummy with a real provider to get actual AI`,
      `responses: openai | anthropic | google | ollama | azure-openai`,
      `─────────────────────────────────────────────────────────────────`,
    ].join('\n');

    const promptTokens = Math.ceil(userMessage.length / 4);
    const completionTokens = Math.ceil(content.length / 4);

    return {
      content,
      model: request.model ?? 'dummy-1',
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
    };
  }
}
